name: Pull code, rebuild files and restart pm2 processes

on:
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: rebuild server
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          cd redditv2
          git pull
          npm install
          npx tsc
          cd client
          npm run build
          pm2 restart server client
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.PRIVATE_KEY}}